- name: Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
  when: is_ubuntu13_plus
- name: Install Docker
  package: name=docker-engine allow_unauthenticated=yes
  when: is_ubuntu13_plus
- name: Install Docker for Mac
  homebrew_cask: name=docker
  when: is_osx
- name: Install Docker tool box for Mac
  homebrew_cask: name=docker-toolbox
  when: is_osx
